### ISSUE TITLE
How to run Mutation that returns the result of some function

### ISSUE THREAD

**Issue by collegeimprovements** [apollographql/graphql-server-example#5]
Hi, 

Thanks for making this example :) 

How to define `mutation` that takes some input-argument and then return the result based on some function call ? 
It's not an actual issue but i'm finding it grasp `Mutation` in `apollo-server` and i couldn't find an example online! 

```js
let AWS = require("aws-sdk");
const translate = new AWS.Translate({
  apiVersion: "2017-07-01",
  region: "us-east-1"
});
const { ApolloServer, gql } = require("apollo-server");

let params = {
  SourceLanguageCode: "auto" /* required */,
  TargetLanguageCode: "en" /* required */,
  Text: "你好，世界\n你好吗\n" /* required */
};

trans = (text = "你好") =>
  translate.translateText(params, function(err, data) {
    params.Text = text;
    if (err) console.log(err, err.stack);
    return data;
  });



const typeDefs = gql`
  type Query {
    "A simple type for getting started!"
    defaultTranslation: Tanslation
  }

  type Tanslation {
    TranslatedText: String
    SourceLanguageCode: String
    TargetLanguageCode: String
  }

// HOW TO RETURN RESULT OF trans().response.data FOR THIS MUTATION :\ 
  type Mutation {
    translate(text: String): String
  }
`;


const server = new ApolloServer({ typeDefs, resolvers });

server.listen().then(({ url }) => {
  console.log(`🚀  Server ready at ${url}`);
});


const resolvers = {
  Query: {
    defaultTranslation:  () => {let result = trans(); result.response.data }
  },
  Mutation: {
    translate: "HELP!!!"
  }
};

```

**Comment by abernix** [comment]
I'm glad this example has been helpful for you!  Unfortunately, this isn't the right place to request help on a topic like this (though I do think an an example would be helpful in the future, I think it would be in a different place).

Mutations work a lot like queries, so you're not far off.  But the most clear error in this example is that you're not `return`ing anything from the `defaultTranslation`.  Without a `return`, the `result.response.data` will do nothing.  So:

```js
    defaultTranslation:  () => {let result = trans(); result.response.data }
```
should be
```js
    defaultTranslation:  () => {let result = trans(); return result.response.data }
```

Additionally, if you change the `translate` resolver to be a function and have it `return "HELP!!!";` you should get the response from your mutation that you're expecting.

Regardless though, again this isn't the right place for questions.  You might want to ask on the [Apollo Slack](https://www.apollographql.com/slack) if you have any further questions!
